- name: Variable
  hosts: localhost
  connection: local
  vars:
   URL: play.google.com
  tasks:
   - name: print Variable
     ansible.builtin.debug:
       msg: URL ={{ URL }}
## Ansible access variables with two flower braces
   - name: print task variable
     ansible.builtin.debug:
       msg: URL ={{ URL }}
     vars:
       URL: tasks.google.com