- name: Demo on Loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - orange
      - apple
  tasks:
    - name: print Fruits
      ansible.builtin.debug:
        msg: Fruits Name - "{{ item }}"
      loop: "{{ fruits }}"

    - name: print Fruits local values
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop:
        - banana
        - kiwi
